# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('sport', 'Sport'), ('politics', 'Politics'), ('news', 'News')], max_length=256, null=True),
        ),
    ]
