# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('sport', 'Sport'), ('politics', 'Politics'), ('news', 'News')], default='news', max_length=256),
        ),
    ]
