# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 19:01
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_auto_20170501_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
