# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0004_auto_20170504_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('sport', 'Sport'), ('politics', 'Politics'), ('news', 'News'), ('fun', 'Fun'), ('music', 'Music')], default='news', max_length=256),
        ),
    ]
