# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 16:45
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_auto_20170513_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published_date',
        ),
        migrations.AddField(
            model_name='article',
            name='published_at',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', when=set(['published'])),
        ),
    ]
