# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0007_auto_20170916_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_the_chosen_one',
            field=models.BooleanField(default=True),
        ),
    ]
