# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 20:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0009_auto_20170916_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_the_chosen_one',
        ),
    ]
