# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0010_remove_article_is_the_chosen_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_the_chosen_one',
            field=models.BooleanField(default=False),
        ),
    ]
