# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-16 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paypal_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='magazine',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.DeleteModel(
            name='Podcast',
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
